Programm started at: 2025-06-30 02:28:14

Running in version 1.2[2025-06-30 23:32:47]
Git repositories synchronized
	

	NoneType: None


[2025-06-30 23:32:47]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-01 02:28:54

Running in version 1.2

[2025-07-01 23:32:29]
Git repositories synchronized
	

	NoneType: None


[2025-07-01 23:32:29]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-02 02:28:42

Running in version 1.2

[2025-07-02 10:02:53]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-07-02 23:32:17]
Git repositories synchronized
	

	NoneType: None


[2025-07-02 23:32:17]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-03 02:28:08

Running in version 1.2

[2025-07-03 18:41:35]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


