Programm started at: 2025-10-27 01:02:26

Running in version 1.2[2025-10-27 06:00:33]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-10-27 23:33:02]
Git repositories synchronized
	

	NoneType: None


[2025-10-27 23:33:02]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-10-28 01:03:30

Running in version 1.2

[2025-10-28 23:32:05]
Git repositories synchronized
	

	NoneType: None


[2025-10-28 23:32:05]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-10-29 01:03:14

Running in version 1.2

[2025-10-29 23:32:49]
Git repositories synchronized
	

	NoneType: None


[2025-10-29 23:32:49]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-10-30 01:02:39

Running in version 1.2

[2025-10-30 23:32:14]
Git repositories synchronized
	

	NoneType: None


[2025-10-30 23:32:14]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-10-31 01:03:45

Running in version 1.2

[2025-10-31 17:47:08]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


