Programm started at: 2025-09-01 02:02:49

Running in version 1.2[2025-09-01 23:32:23]
Git repositories synchronized
	

	NoneType: None


[2025-09-01 23:32:23]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-02 02:02:28

Running in version 1.2

[2025-09-02 04:35:32]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-09-02 23:00:59]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-09-02 23:32:05]
Git repositories synchronized
	

	NoneType: None


[2025-09-02 23:32:05]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-03 02:01:49

Running in version 1.2

[2025-09-03 23:32:24]
Git repositories synchronized
	

	NoneType: None


[2025-09-03 23:32:24]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-04 02:02:47

Running in version 1.2

[2025-09-04 21:38:15]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-09-04 23:32:23]
Git repositories synchronized
	

	NoneType: None


[2025-09-04 23:32:23]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-05 02:02:27

Running in version 1.2

[2025-09-05 23:33:06]
Git repositories synchronized
	

	NoneType: None


[2025-09-05 23:33:06]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-06 02:01:52

Running in version 1.2

[2025-09-06 23:32:27]
Git repositories synchronized
	

	NoneType: None


[2025-09-06 23:32:27]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-07 02:02:54

Running in version 1.2

